alpaca:
  base_url: https://paper-api.alpaca.markets
  key_id: PKOOFJDSJAPGDGTOFIQ9
  secret_key: fxMORdYJ4pelOfuMSR7zkbPlghS9c6QOdNPzw5fv
cluster_1_mean_reversion:
  cointegration:
    enabled: true
    lookback_period: 252
    method: engle_granger
    significance_level: 0.05
  enabled: true
  entry_threshold: 2.0
  exit_threshold: 0.5
  kalman_filter:
    enabled: true
    observation_covariance: 1.0
    transition_covariance: 0.01
  stationarity:
    adf_test: true
    enabled: true
    kpss_test: true
  stop_loss: -3.0
  validation:
    bootstrap_samples: 1000
    confidence_level: 0.95
    t_test: true
cluster_2_momentum:
  arima:
    auto_arima: true
    enabled: true
    forecast_steps: 5
    max_d: 2
    max_p: 5
    max_q: 5
    seasonal: false
  autocorrelation:
    enabled: true
    max_lags: 20
    significance_level: 0.05
  enabled: true
  granger_causality:
    enabled: true
    max_lags: 10
    significance_level: 0.05
  lookback_period: 20
  momentum_threshold: 0.02
  performance_metrics:
    calmar_ratio: true
    min_periods: 30
    sharpe_ratio: true
    sortino_ratio: true
cluster_3_volatility:
  enabled: true
  garch:
    enabled: true
    forecast_horizon: 5
    model_type: GARCH
    p: 1
    q: 1
  markov_switching:
    enabled: true
    n_regimes: 2
    switching_variance: true
  monte_carlo:
    enabled: true
    forecast_horizon: 30
    n_simulations: 10000
  risk_metrics:
    cvar_confidence: 0.05
    var_confidence: 0.05
  vol_lookback: 30
  vol_threshold_high: 0.35
  vol_threshold_low: 0.15
cluster_4_multi_factor:
  bayesian:
    enabled: true
    prior_precision: 1.0
    update_frequency: 20
  enabled: true
  factor_models:
    carhart_momentum: true
    custom_factors:
    - momentum
    - value
    - quality
    fama_french: true
  ica:
    enabled: true
    n_components: 5
  optimization:
    max_weight: 0.1
    method: mean_variance
    min_weight: 0.01
    rebalance_frequency: 20
  pca:
    enabled: true
    n_components: 5
    variance_threshold: 0.95
cluster_5_regime_detection:
  adaptation_speed: 0.1
  enabled: true
  hmm:
    covariance_type: full
    enabled: true
    n_states: 3
  markov_switching:
    enabled: true
    n_regimes: 2
    switching_mean: true
    switching_variance: true
  regime_threshold: 0.7
  state_space:
    enabled: true
    kalman_filter: true
  walk_forward:
    enabled: true
    step_size: 21
    test_period: 63
    train_period: 252
cluster_6_execution:
  enabled: true
  execution_algos:
    participation_rate: 0.1
    twap: true
    vwap: true
  market_impact:
    almgren_chriss: true
    kyle_lambda: 0.001
  max_order_size: 1000000
  min_order_size: 10000
  order_book:
    enabled: false
    imbalance_threshold: 0.6
  participation_limit: 0.25
  slippage:
    confidence_interval: 0.95
    distribution_model: normal
    enabled: true
cluster_7_validation:
  bootstrap:
    block_size: 20
    enabled: true
    n_samples: 1000
  confidence_level: 0.95
  enabled: true
  monte_carlo_runs: 1000
  out_of_sample:
    enabled: true
    rolling_window: true
    test_ratio: 0.3
  performance_monitoring:
    alert_threshold: -0.1
    rolling_drawdown: true
    rolling_sharpe: true
    window_size: 60
  statistical_tests:
    hansen_spa_test: true
    significance_level: 0.05
    whites_reality_check: true
  stress_test_scenarios: 5
cluster_strategy:
  cluster_weights:
    cluster_1: 0.25
    cluster_2: 0.2
    cluster_3: 0.15
    cluster_4: 0.2
    cluster_5: 0.1
    cluster_6: 0.05
    cluster_7: 0.1
  custom_clusters:
  - cluster_1
  - cluster_7
  mode: predefined
  predefined_strategy: factor_portfolio
data_source: yahoo
end_date: '2024-12-01'
initial_cash: 200000
majority_voting:
  enabled: true
  minimum_timeframes: 1
  require_majority: false
  weight_by_strength: true
ml_algorithms:
  arima:
    confidence_level: 0.95
    enabled: true
    forecast_steps: 5
    order:
    - 1
    - 1
    - 1
    seasonal_order:
    - 1
    - 1
    - 1
    - 12
    weight: 0.33
  enabled: true
  ensemble:
    combination_method: weighted_average
    confidence_threshold: 0.6
    enabled: true
    minimum_algorithms: 2
    weight: 0.33
  garch:
    enabled: true
    forecast_horizon: 5
    p: 1
    q: 1
    volatility_threshold: 0.02
    weight: 0.33
  pca:
    enabled: false
    lookback_period: 50
    n_components: 5
    variance_threshold: 0.95
    weight: 0.25
mode: paper
predefined_strategies:
  adaptive_trend:
    active_clusters:
    - cluster_2
    - cluster_5
    - cluster_7
    cluster_weights:
      cluster_2: 0.6
      cluster_5: 0.3
      cluster_7: 0.1
    description: Momentum with adaptive regime detection
  factor_portfolio:
    active_clusters:
    - cluster_4
    - cluster_7
    cluster_weights:
      cluster_4: 0.9
      cluster_7: 0.1
    description: Multi-factor statistical arbitrage
  pairs_trading:
    active_clusters:
    - cluster_1
    - cluster_7
    cluster_weights:
      cluster_1: 0.9
      cluster_7: 0.1
    description: Mean reversion with robust validation
  volatility_breakout:
    active_clusters:
    - cluster_3
    - cluster_5
    - cluster_7
    cluster_weights:
      cluster_3: 0.7
      cluster_5: 0.2
      cluster_7: 0.1
    description: Volatility trading with regime detection
primary_timeframe: 1d
start_date: '2024-01-01'
strategy: statistical_clusters
strategy_params:
  atr_periods:
  - 14
  - 21
  bb_periods:
  - 20
  - 30
  bb_std_devs:
  - 2.0
  - 2.5
  fast_ma_windows:
  - 5
  - 10
  - 15
  - 20
  ichimoku_base:
  - 26
  - 30
  ichimoku_conversion:
  - 9
  - 12
  ichimoku_span_b:
  - 52
  - 60
  min_timeframes_agree: 1
  mse_periods:
  - 20
  - 30
  rsi_overbought: 70
  rsi_oversold: 30
  rsi_periods:
  - 14
  - 21
  signal_strength_threshold: 0.5
  slow_ma_windows:
  - 20
  - 30
  - 50
  - 100
  support_resistance_periods:
  - 20
  - 30
  - 50
tax_config:
  enabled: true
  holding_period_days: 365
  long_term_rate: 0.1
  ltcg_exemption_limit: 100000
  short_term_rate: 0.15
  tax_loss_harvesting: true
ticker: RELIANCE.NS
timeframes:
- 1d
trading_costs:
  bid_ask_spread: 0.005
  commission_per_trade: 0.0
  commission_rate: 0.0
  enabled: true
  gst_rate: 0.18
  margin_rate: 0.08
  sebi_charges_per_crore: 10.0
  slippage: 0.01
  stamp_charges_buy: 0.00015
  stamp_charges_sell: 0.0
  stt_rate_buy: 0.001
  stt_rate_sell: 0.001
  transaction_charges: 2.97e-05
