data_source: yahoo
mode: paper
ticker: RELIANCE.NS
start_date: "2023-06-01"
end_date: "2024-08-22"
initial_cash: 200000
strategy: statistical_clusters
cluster_strategy:
  mode: predefined
  predefined_strategy: adaptive_trend
  # Increase number of clusters for ensemble diversity (set to 100 for tuning)
  num_clusters: 100
  news_integration:
    enabled: true
    csv_path: data/news.csv
    window_hours: 24
    min_items: 3
    weight: 0.15
    bullish_threshold: 0.25
    bearish_threshold: -0.25
  custom_clusters:
    - cluster_1
    - cluster_7
  cluster_weights:
    cluster_1: 0.25
    cluster_2: 0.2
    cluster_3: 0.15
    cluster_4: 0.2
    cluster_5: 0.1
    cluster_6: 0.05
    cluster_7: 0.1
cluster_1_mean_reversion:
  enabled: true
  cointegration:
    enabled: true
    method: engle_granger
    significance_level: 0.05
    lookback_period: 252
  stationarity:
    enabled: true
    adf_test: true
    kpss_test: true
  kalman_filter:
    enabled: true
    transition_covariance: 0.01
    observation_covariance: 1.0
  validation:
    t_test: true
    bootstrap_samples: 1000
    confidence_level: 0.95
  entry_threshold: 2.0
  exit_threshold: 0.5
  stop_loss: -3.0
cluster_2_momentum:
  enabled: true
  autocorrelation:
    enabled: true
    max_lags: 20
    significance_level: 0.05
  arima:
    enabled: true
    auto_arima: true
    max_p: 5
    max_d: 2
    max_q: 5
    seasonal: false
    forecast_steps: 5
  granger_causality:
    enabled: true
    max_lags: 10
    significance_level: 0.05
  performance_metrics:
    sharpe_ratio: true
    sortino_ratio: true
    calmar_ratio: true
    min_periods: 30
  lookback_period: 20
  momentum_threshold: 0.02
cluster_3_volatility:
  enabled: true
  garch:
    enabled: true
    model_type: GARCH
    p: 1
    q: 1
    forecast_horizon: 5
  markov_switching:
    enabled: true
    n_regimes: 2
    switching_variance: true
  risk_metrics:
    var_confidence: 0.05
    cvar_confidence: 0.05
  monte_carlo:
    enabled: true
    n_simulations: 10000
    forecast_horizon: 30
  vol_lookback: 30
  vol_threshold_low: 0.15
  vol_threshold_high: 0.35
cluster_4_multi_factor:
  enabled: true
  pca:
    enabled: true
    n_components: 5
    variance_threshold: 0.95
  ica:
    enabled: true
    n_components: 5
  factor_models:
    fama_french: true
    carhart_momentum: true
    custom_factors:
      - momentum
      - value
      - quality
  bayesian:
    enabled: true
    prior_precision: 1.0
    update_frequency: 20
  optimization:
    method: mean_variance
    rebalance_frequency: 20
    max_weight: 0.1
    min_weight: 0.01
cluster_5_regime_detection:
  enabled: true
  hmm:
    enabled: true
    n_states: 3
    covariance_type: full
  state_space:
    enabled: true
    kalman_filter: true
  markov_switching:
    enabled: true
    n_regimes: 2
    switching_mean: true
    switching_variance: true
  walk_forward:
    enabled: true
    train_period: 252
    test_period: 63
    step_size: 21
  regime_threshold: 0.7
  adaptation_speed: 0.1
cluster_6_execution:
  enabled: true
  order_book:
    enabled: false
    imbalance_threshold: 0.6
  execution_algos:
    vwap: true
    twap: true
    participation_rate: 0.1
  market_impact:
    kyle_lambda: 0.001
    almgren_chriss: true
  slippage:
    enabled: true
    distribution_model: normal
    confidence_interval: 0.95
  max_order_size: 1000000
  min_order_size: 10000
  participation_limit: 0.25
cluster_7_validation:
  enabled: true
  bootstrap:
    enabled: true
    n_samples: 1000
    block_size: 20
  statistical_tests:
    whites_reality_check: true
    hansen_spa_test: true
    significance_level: 0.05
  out_of_sample:
    enabled: true
    test_ratio: 0.3
    rolling_window: true
  performance_monitoring:
    rolling_sharpe: true
    rolling_drawdown: true
    window_size: 60
    alert_threshold: -0.1
  stress_test_scenarios: 5
  confidence_level: 0.95
  monte_carlo_runs: 1000
predefined_strategies:
  pairs_trading:
    active_clusters:
      - cluster_1
      - cluster_7
    description: Mean reversion with robust validation
    cluster_weights:
      cluster_1: 0.9
      cluster_7: 0.1
  volatility_breakout:
    active_clusters:
      - cluster_3
      - cluster_5
      - cluster_7
    description: Volatility trading with regime detection
    cluster_weights:
      cluster_3: 0.7
      cluster_5: 0.2
      cluster_7: 0.1
  factor_portfolio:
    active_clusters:
      - cluster_4
      - cluster_7
    description: Multi-factor statistical arbitrage
    cluster_weights:
      cluster_4: 0.9
      cluster_7: 0.1
  adaptive_trend:
    active_clusters:
      - cluster_2
      - cluster_5
      - cluster_7
    description: Momentum with adaptive regime detection
    cluster_weights:
      cluster_2: 0.6
      cluster_5: 0.3
      cluster_7: 0.1
trading_costs:
  enabled: true
  commission_per_trade: 0.0
  commission_rate: 0.0
  stt_rate_buy: 0.001
  stt_rate_sell: 0.001
  transaction_charges: 2.97e-05
  sebi_charges_per_crore: 10.0
  stamp_charges_buy: 0.00015
  stamp_charges_sell: 0.0
  gst_rate: 0.18
  bid_ask_spread: 0.005
  slippage: 0.01
  margin_rate: 0.08
tax_config:
  enabled: true
  short_term_rate: 0.15
  long_term_rate: 0.1
  ltcg_exemption_limit: 100000
  holding_period_days: 365
  tax_loss_harvesting: true
ml_algorithms:
  enabled: true
  pca:
    enabled: false
    weight: 0.25
    n_components: 5
    lookback_period: 50
    variance_threshold: 0.95
  arima:
    enabled: true
    weight: 0.33
    order:
      - 1
      - 1
      - 1
    seasonal_order:
      - 1
      - 1
      - 1
      - 12
    forecast_steps: 5
    confidence_level: 0.95
  garch:
    enabled: true
    weight: 0.33
    p: 1
    q: 1
    volatility_threshold: 0.02
    forecast_horizon: 5
  ensemble:
    enabled: true
    weight: 0.33
    combination_method: weighted_average
    minimum_algorithms: 1
    confidence_threshold: 0.6
  news_sentiment:
    enabled: true
    weight: 0.34
    csv_path: data/news.csv
    window_hours: 24
    min_items: 3
    bullish_threshold: 0.25
    bearish_threshold: -0.25
    ticker: ""
timeframes:
  - 1d
  - 15m
  - 1h
  - 1mo
  - 1m
primary_timeframe: 1d
majority_voting:
  enabled: true
  minimum_timeframes: 1
  require_majority: false
  weight_by_strength: true
strategy_params:
  fast_ma_windows:
    - 5
    - 10
    - 15
    - 20
  slow_ma_windows:
    - 20
    - 30
    - 50
    - 100
  rsi_periods:
    - 14
    - 21
  rsi_oversold: 30
  rsi_overbought: 70
  bb_periods:
    - 20
    - 30
  bb_std_devs:
    - 2.0
    - 2.5
  atr_periods:
    - 14
    - 21
  support_resistance_periods:
    - 20
    - 30
    - 50
  ichimoku_conversion:
    - 9
    - 12
  ichimoku_base:
    - 26
    - 30
  ichimoku_span_b:
    - 52
    - 60
  mse_periods:
    - 20
    - 30
  min_timeframes_agree: 1
  signal_strength_threshold: 0.5
alpaca:
  key_id: PKOOFJDSJAPGDGTOFIQ9
  secret_key: fxMORdYJ4pelOfuMSR7zkbPlghS9c6QOdNPzw5fv
  base_url: https://paper-api.alpaca.markets
